/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTableRef: typeof import('element-plus/es')['ElTableRef']
}
