/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Collapse: typeof import('./src/components/base/Collapse/src/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/base/CollapseItem/src/CollapseItem.vue')['default']
    ConfigProvider: typeof import('./src/components/ConfigProvider/src/ConfigProvider.vue')['default']
    CustomView: typeof import('./src/components/base/ProTable/components/CustomView/src/CustomView.vue')['default']
    Dialog: typeof import('./src/components/base/Dialog/src/Dialog.vue')['default']
    DragBtn: typeof import('./src/components/base/ProTable/components/Table/src/DragBtn.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Filter: typeof import('./src/components/base/ProTable/components/Filter/src/Filter.vue')['default']
    FilterCustomView: typeof import('./src/components/base/ProTable/components/CustomView/src/FilterCustomView.vue')['default']
    Form: typeof import('./src/components/base/Form/src/Form.vue')['default']
    FormItem: typeof import('./src/components/base/FormItem/src/FormItem.vue')['default']
    GlobalCustomView: typeof import('./src/components/base/ProTable/components/CustomView/src/GlobalCustomView.vue')['default']
    Icon: typeof import('./src/components/base/Icon/src/Icon.vue')['default']
    OperationLogChangeDetail: typeof import('./src/components/operationLog/src/components/operation-log-change-detail.vue')['default']
    OperationLogDialog: typeof import('./src/components/operationLog/src/operation-log-dialog.vue')['default']
    OperationLogList: typeof import('./src/components/operationLog/src/operation-log-list.vue')['default']
    OperationLogRequestParams: typeof import('./src/components/operationLog/src/components/operation-log-request-params.vue')['default']
    Pagination: typeof import('./src/components/base/ProTable/components/Pagination/src/Pagination.vue')['default']
    ProTable: typeof import('./src/components/base/ProTable/src/ProTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/base/ProTable/components/Table/src/Table.vue')['default']
    TableColumn: typeof import('./src/components/base/ProTable/components/Table/src/TableColumn.vue')['default']
    TableCustomView: typeof import('./src/components/base/ProTable/components/CustomView/src/TableCustomView.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
